export enum DirectFlow {
  None, ServerPicker, ConnectionReport, Profiles, Access,
  AuthLogin, AuthEmail, AuthCode, AuthRegister, AuthRecovery, AuthBot, AuthPhone, AuthPhoneCode, AuthSuccess,
  Plans, Constructor, Payment, PaymentProcessing, PaymentWaiting, PaymentCancelled, PaymentError, PaymentSuccess,
  Balance, BalanceTopUp, Management, Subscription, Security, Connection, Diagnostics, Activity, SystemSettings, About,
  ServiceLog, ApplicationSettings, CoreSettings, TunnelSettings, OnDemandSettings, ImportFile, ImportText, Legal, Privacy,
  Account, Devices, PaymentHistory
}
