#!/usr/bin/env bash
# Clone / update core/sing-box from Leadaxe/sing-box-lx
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CORE="${ROOT}/core/sing-box"
REMOTE="${SING_BOX_REMOTE:-https://github.com/Leadaxe/sing-box-lx.git}"
BRANCH="${SING_BOX_BRANCH:-lx}"

mkdir -p "${ROOT}/core"

if [[ -d "${CORE}/.git" ]]; then
  echo "updating existing ${CORE}"
  cd "${CORE}"
  git fetch origin "${BRANCH}"
  git checkout "${BRANCH}"
  git pull --ff-only origin "${BRANCH}" || true
  git submodule update --init --recursive
else
  echo "cloning ${REMOTE} (${BRANCH}) → ${CORE}"
  rm -rf "${CORE}"
  git clone --branch "${BRANCH}" --recurse-submodules --depth 1 "${REMOTE}" "${CORE}"
fi

cd "${CORE}"
git remote add upstream https://github.com/SagerNet/sing-box.git 2>/dev/null || true

# Refresh pins in core/VERSION
UPSTREAM="unknown"
GOV="unknown"
[[ -f upstream.version ]] && UPSTREAM="$(tr -d ' \n' < upstream.version)"
[[ -f go.version ]] && GOV="$(tr -d ' \n' < go.version)"
DESC="$(git describe --tags --always 2>/dev/null || git rev-parse --short HEAD)"

cat > "${ROOT}/core/VERSION" <<EOF
# VPN Direct Core pins (generated by scripts/bootstrap_core.sh)
CORE_VERSION=0.1.0
CORE_NAME=VPNDirectCore
SING_BOX_REMOTE=${REMOTE}
SING_BOX_BRANCH=${BRANCH}
SING_BOX_REV=${DESC}
UPSTREAM_VERSION=${UPSTREAM}
GO_VERSION=${GOV}
BUILD_PROFILE=vpn_direct_ios
BUILD_TAGS=with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_naive_outbound,with_clash_api,with_xhttp,with_awg,with_lx_idle_suspend
STOCK_LIBBOX_BACKUP=Libbox.xcframework.stock
EOF

# Apply in-tree protocol overlays (mieru) so Core builds without a private sing-box fork push
bash "${ROOT}/scripts/prepare_core.sh"

echo "bootstrapped ${DESC} (upstream ${UPSTREAM}, go ${GOV})"
