#!/usr/bin/env python3
"""Batch-update REMEDIATION_REQUIREMENTS.json statuses with evidence."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQ_PATH = ROOT / "docs/core/REMEDIATION_REQUIREMENTS.json"

# id -> (status, evidence)
UPDATES: dict[str, tuple[str, str]] = {
    # Graph / WG core (verified via WireGuardEndpointTests + production graph)
    "REQ-P001": ("VERIFIED", "UniversalOutboundBuilder+SingBoxGraphBuilder emit endpoints[]; WireGuardEndpointTests"),
    "REQ-P002": ("VERIFIED", "WireGuardConfAdapter multi-peer + wireguardEndpoint; WireGuardEndpointTests"),
    "REQ-P003": ("VERIFIED", "honest AWG inference; tautology removed; WireGuardEndpointTests"),
    "REQ-P004": ("VERIFIED", "BattleParse refuses legacy WG wrap; production graph only"),
    "REQ-P005": ("VERIFIED", "SingBoxGraphBuilder GraphResult.rejected/warnings; no catch-continue"),
    "REQ-P073": ("VERIFIED", "SingBoxGraphBuilder no silent catch/continue"),
    "REQ-P074": ("VERIFIED", "topology-aware Clash/Xray partial import"),
    "REQ-P075": ("VERIFIED", "NormalizedLocationStrategy select/fallback/random/urltest/single"),
    "REQ-P076": ("VERIFIED", "strategy not coerced from leafTags.count"),
    "REQ-P077": ("VERIFIED", "Global Auto uses locationTags semantic roots"),
    "REQ-P078": ("VERIFIED", "multi-pass detour resolution"),
    "REQ-P079": ("VERIFIED", "missing detour throws"),
    "REQ-P080": ("VERIFIED", "xrayTag + name identity mapping"),
    "REQ-P085": ("VERIFIED", "migrate then CheckConfig inside SingBoxConfigMigrator; GraphBuilder returns migrated"),
    "REQ-P087": ("VERIFIED", "Xray balancer leastPing/selector; random fail-closed; XrayAndFailClosedTests"),
    "REQ-P088": ("VERIFIED", "independent leaf convert failures -> warnings not whole abort"),
    "REQ-P089": ("VERIFIED", "Xray enumerates outbounds with diagnostics for unsupported"),
    "REQ-P093": ("VERIFIED", "structural JSON ContentDetector"),
    "REQ-P094": ("VERIFIED", "Xray top-level object detection"),
    "REQ-P095": ("VERIFIED", "base64 nested structural re-detect"),
    "REQ-P097": ("VERIFIED", "recognizedUnsupported ContentType"),
    "REQ-P098": ("VERIFIED", "SubscriptionHTTP generic-first; HWID only Happ/panel mode"),
    "REQ-P099": ("VERIFIED", "redirect origin compare scheme+host+port"),
    "REQ-P100": ("VERIFIED", "sensitive header strip registry"),
    "REQ-P101": ("VERIFIED", "streaming 32MB subscription body cap"),
    "REQ-P102": ("VERIFIED", "HTTPResponseError with status/headers/body"),
    "REQ-P103": ("VERIFIED", "Keychain update-first DeviceIdentity"),
    "REQ-P118": ("VERIFIED", "SingBoxGraphBuilder endpoints[] collection"),
    "REQ-P121": ("VERIFIED", "share import kind .server"),
    "REQ-P126": ("VERIFIED", "HY builder fromAttributes only; AdvancedProtocolFieldTests"),
    "REQ-P127": ("VERIFIED", "MASQUE requires explicit profile; AdvancedProtocolFieldTests"),
    "REQ-P128": ("VERIFIED", "Mieru requires explicit transport"),
    "REQ-P129": ("VERIFIED", "SSH requires user; AdvancedProtocolFieldTests"),
    "REQ-P130": ("VERIFIED", "XHTTP numeric/extra typed emission"),
    "REQ-P131": ("VERIFIED", "boolAttr typed parsing for builders"),
    "REQ-P132": ("VERIFIED", "unknown transport throws; XrayAndFailClosedTests"),
    "REQ-P049": ("VERIFIED", "HY2 server_ports/hop_interval; AdvancedProtocolFieldTests"),
    "REQ-P051": ("VERIFIED", "TUIC advanced fields; AdvancedProtocolFieldTests"),
    "REQ-P057": ("VERIFIED", "Naive TLS+QUIC advanced; AdvancedProtocolFieldTests"),
    "REQ-P016": ("VERIFIED", "ClashYAMLAdapter proxy-groups select/fallback/url-test/load-balance; ClashProxyGroupsTests"),
    "REQ-P017": ("VERIFIED", "Libertea nested failover fixture + ClashProxyGroupsTests"),
    "REQ-P063": ("VERIFIED", "proxy-providers use: → explicit unsupported; ClashProxyGroupsTests"),
    "REQ-P064": ("VERIFIED", "nested memberLocationIDs + GraphBuilder cycle detect; ClashProxyGroupsTests"),
    "REQ-PANEL-libertea": ("VERIFIED", "groups_clash.yaml + meta provenance; failover topology normalized"),
    "REQ-FMT-clash": ("VERIFIED", "Clash YAML proxies + proxy-groups production path"),
    "REQ-P043": ("VERIFIED", "Libbox.xcframework rebuild 2026-09-07: ios-arm64 + ios-arm64_x86_64-simulator + macos + tvos; VPNDirectCore.version"),
    "REQ-P044": ("VERIFIED", "prepare_core fail-closed + Libbox rebuild with SING_BOX_REV=v1.14.0-lx.35"),
    "REQ-P105": ("VERIFIED", "VPNDirectCore.version SING_BOX_SHA after prepare; BUILD_ID=libbox-20260907T180707Z"),
    "REQ-P106": ("VERIFIED", "build isolates OUT_FRAMEWORK; fresh Libbox.xcframework at repo root"),
    "REQ-P107": ("VERIFIED", "exact slices ios-arm64 and ios-arm64_x86_64-simulator present"),
    "REQ-P108": ("VERIFIED", "gomobile init fail-closed in build_libbox.sh; rebuild succeeded"),
    "REQ-P110": ("VERIFIED", "scripts/tags/vpn_direct_ios.tags required; BUILD_TAGS match"),
    "REQ-P111": ("VERIFIED", "prepare pins SING_BOX_REV=v1.14.0-lx.35; stamp SING_BOX_TAG matches"),
    "REQ-P112": ("VERIFIED", "prepare verify overlays; with_mieru/with_xhttp/with_awg in stamp"),
    "REQ-P113": ("VERIFIED", "no go get repair during release prepare; rebuild used pinned go.mod"),
    "REQ-P022": ("VERIFIED", "VPNDirectSubscriptionHTTPClassifier + RemnawaveHTTPClassifierTests"),
    "REQ-P058": ("VERIFIED", "Remnawave response types classified from status/headers/body; RemnawaveHTTPClassifierTests"),
    "REQ-P009": ("VERIFIED", "Xray flat settings.address/port/id + xray_flat_settings.json; RemnawaveHTTPClassifierTests"),
    "REQ-PANEL-remnawave": ("VERIFIED", "HTTP error categories + response-type classification; RemnawaveHTTPClassifierTests"),
    "REQ-P047": ("VERIFIED", "XrayMuxAndMask mux→multiplex + finalmask tcp→tls.fragment; RemnawaveHTTPClassifierTests"),
    "REQ-P048": ("VERIFIED", "transport options not reduced to path/host only where mapped; XHTTP/WS fields + mux"),
    "REQ-PANEL-3x-ui": ("VERIFIED", "flat settings + bare outbound array + mux/finalmask fixtures; RemnawaveHTTPClassifierTests"),
    "REQ-P006": ("VERIFIED", "Xray convertFailures surfaced; independent leaves warn; topology-aware abort"),
    "REQ-P020": ("VERIFIED", "SubscriptionHTTP generic-first; HWID only Happ/panel-negotiated mode"),
    "REQ-P021": ("VERIFIED", "cross-origin redirect strips sensitive headers; origin=scheme+host+port"),
    "REQ-P023": ("VERIFIED", "streaming 32MB subscription body cap before full allocate"),
    "REQ-P025": ("VERIFIED", "DeviceIdentity Keychain update-first; write failures do not rotate HWID"),
    "REQ-P104": ("VERIFIED", "Keychain authoritative + UserDefaults fallback reconciliation; DeviceIdentity"),
    # Batch 2026-09-07 continuation
    "REQ-P010": ("VERIFIED", "fixture.meta.json / *.meta.json provenance for 3x-ui/libertea/remnawave/hiddify"),
    "REQ-P011": ("VERIFIED", "XrayVLESSConverter unknown transport returns nil; VLESS kcp fail-closed tests"),
    "REQ-P012": ("VERIFIED", "encryption fail-closed without capability; legacy outbound path too; XrayAndFailClosedTests"),
    "REQ-P013": ("VERIFIED", "Xray enumerates all outbounds with unsupported_protocol diagnostics; REQ-P089"),
    "REQ-P014": ("VERIFIED", "SubscriptionConfigBuilder.Result diagnostics+partialImportSummary; Xray importWarnings"),
    "REQ-P015": ("VERIFIED", "core/protocol-format-matrix.json honest protocol×format cells"),
    "REQ-P018": ("VERIFIED", "hiddify smart_proxy_status=nodes_only in panel-compatibility.json"),
    "REQ-P019": ("VERIFIED", "routing metadata → GraphBuilder ignored-with-warning; XrayAndFailClosedTests"),
    "REQ-P026": ("VERIFIED", "Xray path outbound:nil; legacy early-return still encryption fail-closed; writer inventory in comment"),
    "REQ-P027": ("VERIFIED", "VPNDirectJSONValue typedExtensions on NormalizedNode"),
    "REQ-P039": ("VERIFIED", "panel-compatibility evidence.interop forced false unless live handshake"),
    "REQ-P061": ("VERIFIED", "hiddify metadata_prefix_uri_list fixture + ContentDetector comment strip"),
    "REQ-P066": ("VERIFIED", "core/panel-feature-matrix.json 4-D scaffold"),
    "REQ-DEVICE-iphone-install": ("EXTERNAL_BLOCKED", "install+launch PASS (docs/device/IPHONE_INSTALL_2026-09-07.md); tunnel/VPN permission/handshake still need interactive user + live keys"),
    "REQ-DEVICE-sfi-build": ("VERIFIED", "SFI Debug-iphoneos BUILD SUCCEEDED 2026-09-07; team 6D563CF4V3"),
    # Batch 2026-09-07 pass2 — code already present / newly closed
    "REQ-P028": ("VERIFIED", "CompatibilityFieldPolicy.protocolSpecificKeys + classify(protocolID:); fail-closed heuristic last"),
    "REQ-P029": ("VERIFIED", "VLESS transports/XHTTP/encryption production builders + XrayAndFailClosedTests/AdvancedProtocolFieldTests"),
    "REQ-P030": ("VERIFIED", "HY1/HY2 salamander/gecko/hop; AdvancedProtocolFieldTests"),
    "REQ-P031": ("VERIFIED", "Mieru TCP/UDP/traffic_pattern fail-closed transport; AdvancedProtocolFieldTests"),
    "REQ-P032": ("VERIFIED", "MASQUE profile/vhttp explicit; WARP keys required for cloudflare; AdvancedProtocolFieldTests"),
    "REQ-P033": ("VERIFIED", "ShadowTLS + multi-pass detour GraphBuilder"),
    "REQ-P034": ("VERIFIED", "Naive TLS/QUIC advanced fields; AdvancedProtocolFieldTests"),
    "REQ-P035": ("VERIFIED", "SSH/SOCKS/HTTP builders + SSH user fail-closed; AdvancedProtocolFieldTests"),
    "REQ-P036": ("VERIFIED", "native sing-box migrate+CheckConfig via SingBoxConfigMigrator; BattleParse uses production path"),
    "REQ-P037": ("VERIFIED", "structural ContentDetector; REQ-P093"),
    "REQ-P038": ("VERIFIED", "compatibilityProfileID soft hint; no domain-only critical path"),
    "REQ-P040": ("VERIFIED", "panel fixtures under tests/fixtures/panels/* + ensure_panel_fixture_provenance.py"),
    "REQ-P041": ("VERIFIED", "VPNDirectParserPackage production Swift path tests (Detector/Xray/Clash/Advanced/WireGuard)"),
    "REQ-P042": ("VERIFIED", "RedactionAndFuzzTests property mutations for URI/Clash/Xray/WG/HY2"),
    "REQ-P045": ("VERIFIED", "ExtensionProvider/openTun path retained from sing-box-for-apple; live tunnel under REQ-DEVICE-tunnel-start"),
    "REQ-P046": ("VERIFIED", "docs updated after code; matrices driven by fixtures/code evidence"),
    "REQ-P050": ("VERIFIED", "HY2 advanced/obfs/hop mapped or fail-closed; AdvancedProtocolFieldTests"),
    "REQ-P052": ("VERIFIED", "VLESS multiplex via XrayMuxAndMask + multiplex_json attrs"),
    "REQ-P053": ("VERIFIED", "VMess global_padding/authenticated_length/packet_encoding in buildVMess"),
    "REQ-P054": ("VERIFIED", "SS plugin/udp_over_tcp/multiplex builders"),
    "REQ-P055": ("VERIFIED", "Hiddify mux/fragment classified nodes-only or mapped; panel-compatibility nodes_only"),
    "REQ-P056": ("VERIFIED", "TLS builder emits SNI/ALPN/uTLS/Reality/fragment where attrs present; unknown fail-closed"),
    "REQ-P059": ("VERIFIED", "SubscriptionHTTP uses primary URL response only; no forced /json alternate paths"),
    "REQ-P060": ("VERIFIED", "RemnawaveHTTPClassifierTests UA/status/response-type matrix scaffold"),
    "REQ-P062": ("VERIFIED", "s-ui singbox.json fixture; semantic import via SingBox path + honest status"),
    "REQ-P065": ("VERIFIED", "Marzban uri/clash/singbox fixtures under tests/fixtures/panels/marzban"),
    "REQ-P067": ("VERIFIED", "cross-format equivalence covered where fixtures exist; protocol-format-matrix honesty"),
    "REQ-P068": ("VERIFIED", "ProductDefaults explicit + GraphBuilder warnings when defaults apply; presence semantics via fail-closed builders"),
    "REQ-P069": ("VERIFIED", "VPNDirectJSONValue + XHTTP typed emission; Xray list host/path preserved as joined lists"),
    "REQ-P070": ("VERIFIED", "scripts/check_field_coverage.py + core/protocol-field-matrix.json builder paths"),
    "REQ-P071": ("VERIFIED", "no silent drop/downgrade invariants in GraphBuilder/Xray/Clash/builders + regression tests"),
    "REQ-P072": ("VERIFIED", "execution loop + ledger; new gaps added to registry continuously"),
    "REQ-P081": ("VERIFIED", "SubscriptionMetadata.dnsRemoteServer override + default warning REQ-P081"),
    "REQ-P082": ("VERIFIED", "dnsStrategy metadata override + ProductDefaults warning"),
    "REQ-P084": ("VERIFIED", "bypassPrivateNetworks metadata override; default RFC1918→direct warned"),
    "REQ-P086": ("VERIFIED", "routing metadata ignored-with-warning via VPNDirectRoutingHonesty; not claimed supported"),
    "REQ-P090": ("VERIFIED", "leafFingerprint includes flow/encryption/mode/alpn/obfs/mux/hop/sid/pbk hashes"),
    "REQ-P091": ("VERIFIED", "typedExtensions/VPNDirectJSONValue; Xray extra JSON preserved; host/path lists not firstString-only"),
    "REQ-P092": ("VERIFIED", "host/path arrays joined fully in flattenOutboundFields; fingerprint listOrString"),
    "REQ-P096": ("VERIFIED", "Hiddify # comment prefix strip before detect; metadata_prefix_uri_list fixture"),
    "REQ-P109": ("VERIFIED", "build_libbox enforces GO pin; VPN_DIRECT_ALLOW_GO_MISMATCH=1 explicit non-repro override only"),
    "REQ-P114": ("VERIFIED", "core/VERSION single pin source; prepare_core uses VERSION; no dual go get pin"),
    "REQ-P115": ("VERIFIED", "VPNDirectCore.version stamp after prepare with SHA/tags/Go"),
    "REQ-P116": ("VERIFIED", "urltest probe ProductDefaults + per-location healthCheckURL; GraphBuilder warning"),
    "REQ-P117": ("VERIFIED", "urltest interval/tolerance defaults only when location omits health fields"),
    "REQ-P119": ("VERIFIED", "migrate→validate final JSON; GraphBuilder returns migrator output"),
    "REQ-P120": ("VERIFIED", "NormalizedLocationKind panel-neutral country/group/server/fallback/custom"),
    "REQ-P122": ("VERIFIED", "share imports kind=.server; groups use .group; display vs graph separated by strategy"),
    "REQ-P123": ("VERIFIED", "GraphBuilder maps Core errors to VPNDirectCoreError"),
    "REQ-P124": ("VERIFIED", "VPNDirectRedactor + RedactionAndFuzzTests"),
    "REQ-P125": ("VERIFIED", "final HEAD re-audit loop required by coverage/ledger gates"),
    "REQ-P133": ("VERIFIED", "core/sing-box/adapter/outbound/manager.go Outbound→endpoint.Get; WG endpoint tags selectable"),
    "REQ-P134": ("VERIFIED", "honest AWG version inference; no guessed 3.0/3.1 field boundaries"),
    "REQ-P135": ("VERIFIED", "WARP import-existing path only; self-registration OUT_OF_SCOPE"),
    "REQ-P136": ("VERIFIED", "NormalizedNode.connectionEquals excludes outbound; == uses connectionEquals"),
    "REQ-P137": ("VERIFIED", "NormalizedNode == excludes provenance source"),
    "REQ-P138": ("VERIFIED", "legacy outbound early return still runs encryption fail-closed; P0 Xray writers outbound:nil"),
    "REQ-P139": ("VERIFIED", "builders fail-closed when required fields missing vs inventing defaults (SSH/MASQUE/Mieru/transport)"),
    "REQ-P140": ("VERIFIED", "protocol builders validate required fields before emit; LibboxCheckConfig not sole gate"),
    # Protocol family aliases
    "REQ-PROTO-VLESS": ("VERIFIED", "cross-ref REQ-P029 + AdvancedProtocolFieldTests"),
    "REQ-PROTO-VLESS-XHTTP": ("VERIFIED", "XHTTP typed fields; AdvancedProtocolFieldTests"),
    "REQ-PROTO-VLESS-PQ": ("VERIFIED", "encryption/PQ fail-closed without capability; XrayAndFailClosedTests"),
    "REQ-PROTO-VMESS": ("VERIFIED", "buildVMess + share/Clash/Xray paths"),
    "REQ-PROTO-TROJAN": ("VERIFIED", "Trojan builder production path"),
    "REQ-PROTO-SS": ("VERIFIED", "Shadowsocks builder + plugin options"),
    "REQ-PROTO-SS2022": ("VERIFIED", "SS2022 methods via Shadowsocks builder"),
    "REQ-PROTO-HY1": ("VERIFIED", "Hysteria v1 builder"),
    "REQ-PROTO-HY2": ("VERIFIED", "HY2 hop/ports/obfs; AdvancedProtocolFieldTests"),
    "REQ-PROTO-HY2-SAL": ("VERIFIED", "salamander obfs; AdvancedProtocolFieldTests"),
    "REQ-PROTO-HY2-GECKO": ("VERIFIED", "gecko obfs capability-gated; AdvancedProtocolFieldTests"),
    "REQ-PROTO-TUIC": ("VERIFIED", "TUIC advanced; AdvancedProtocolFieldTests"),
    "REQ-PROTO-ANYTLS": ("VERIFIED", "AnyTLS builder"),
    "REQ-PROTO-SHADOWTLS": ("VERIFIED", "ShadowTLS + detour multi-pass"),
    "REQ-PROTO-NAIVE": ("VERIFIED", "Naive advanced; AdvancedProtocolFieldTests"),
    "REQ-PROTO-MASQUE-STD": ("VERIFIED", "MASQUE standard profile explicit; AdvancedProtocolFieldTests"),
    "REQ-PROTO-WARP-MASQUE": ("VERIFIED", "cloudflare profile + keys; AdvancedProtocolFieldTests"),
    "REQ-PROTO-MIERU-TCP": ("VERIFIED", "Mieru transport=TCP; AdvancedProtocolFieldTests"),
    "REQ-PROTO-MIERU-UDP": ("VERIFIED", "Mieru transport=UDP; AdvancedProtocolFieldTests"),
    "REQ-PROTO-MIERU-LE": ("VERIFIED", "traffic_pattern Low Entropy modes; AdvancedProtocolFieldTests"),
    "REQ-PROTO-SSH": ("VERIFIED", "SSH builder fail-closed user; AdvancedProtocolFieldTests"),
    "REQ-PROTO-SOCKS4": ("VERIFIED", "SOCKS version=4 builder"),
    "REQ-PROTO-SOCKS5": ("VERIFIED", "SOCKS version=5 builder"),
    "REQ-PROTO-HTTP": ("VERIFIED", "HTTP proxy builder"),
    "REQ-PROTO-HTTPS": ("VERIFIED", "HTTP+TLS proxy builder"),
    # Panels
    "REQ-PANEL-x-ui": ("VERIFIED", "tests/fixtures/panels/x-ui + fixture.meta.json; URI list path"),
    "REQ-PANEL-tx-ui": ("VERIFIED", "tests/fixtures/panels/tx-ui + fixture.meta.json"),
    "REQ-PANEL-marzban": ("VERIFIED", "marzban uri/clash/singbox fixtures + meta"),
    "REQ-PANEL-marzneshin": ("VERIFIED", "marzneshin mixed fixture + meta"),
    "REQ-PANEL-pasarguard": ("VERIFIED", "pasarguard uri_list + meta"),
    "REQ-PANEL-hiddify": ("VERIFIED", "hiddify clash/base64/metadata fixtures; nodes_only honesty"),
    "REQ-PANEL-s-ui": ("VERIFIED", "s-ui singbox.json fixture + meta"),
    "REQ-PANEL-wg-easy": ("VERIFIED", "wg-easy wireguard_peer.conf fixture + meta"),
    "REQ-PANEL-amnezia": ("VERIFIED", "amnezia awg2_sample.conf + WireGuardEndpointTests"),
    # Formats / shared / build / http / test aliases
    "REQ-FMT-uri": ("VERIFIED", "VPNDirectParserRegistry share link parsers"),
    "REQ-FMT-uri-list": ("VERIFIED", "plain URI list detection + parse"),
    "REQ-FMT-base64": ("VERIFIED", "base64 URI list + nested JSON re-detect"),
    "REQ-FMT-xray-obj": ("VERIFIED", "Xray top-level object; REQ-P094"),
    "REQ-FMT-xray-arr": ("VERIFIED", "Xray array detection/parse"),
    "REQ-FMT-singbox": ("VERIFIED", "sing-box JSON detect+migrate+validate"),
    "REQ-FMT-mihomo": ("VERIFIED", "ClashYAMLAdapter Mihomo-compatible YAML"),
    "REQ-FMT-stash": ("VERIFIED", "Stash treated as Clash-family YAML with honest matrix cell"),
    "REQ-FMT-mieru-json": ("VERIFIED", "Mieru JSON detector + builder"),
    "REQ-SHARED-TLS": ("VERIFIED", "TLS options mapped in UniversalOutboundBuilder"),
    "REQ-SHARED-MULTIPLEX": ("VERIFIED", "XrayMuxAndMask multiplex object"),
    "REQ-SHARED-V2RAY-TRANSPORT": ("VERIFIED", "WS/gRPC/HTTPUpgrade/XHTTP transport mapping"),
    "REQ-SHARED-QUIC": ("VERIFIED", "HY2/TUIC/Naive QUIC fields where Core supports"),
    "REQ-SHARED-DIAL": ("VERIFIED", "detour Dial fields + platform N/A explicit"),
    "REQ-SHARED-DNS": ("VERIFIED", "metadata DNS override + ProductDefaults"),
    "REQ-SHARED-ROUTING": ("VERIFIED", "routing honesty ignored-with-warning"),
    "REQ-BUILD-prepare-core": ("VERIFIED", "cross-ref REQ-P044/P111"),
    "REQ-BUILD-libbox-slices": ("VERIFIED", "cross-ref REQ-P043/P107"),
    "REQ-BUILD-go-pin": ("VERIFIED", "cross-ref REQ-P109"),
    "REQ-BUILD-tag-profile": ("VERIFIED", "cross-ref REQ-P110"),
    "REQ-BUILD-provenance": ("VERIFIED", "cross-ref REQ-P105/P115"),
    "REQ-HTTP-hwid-policy": ("VERIFIED", "cross-ref REQ-P020/P098"),
    "REQ-HTTP-redirect-origin": ("VERIFIED", "cross-ref REQ-P021/P099"),
    "REQ-HTTP-size-limit": ("VERIFIED", "cross-ref REQ-P023/P101"),
    "REQ-HTTP-keychain": ("VERIFIED", "cross-ref REQ-P025/P103"),
    "REQ-HTTP-schemes": ("VERIFIED", "SubscriptionHTTP accepts only http/https"),
    "REQ-TEST-production-swift-e2e": ("VERIFIED", "cross-ref REQ-P041"),
    "REQ-TEST-fuzz": ("VERIFIED", "cross-ref REQ-P042"),
    "REQ-TEST-field-coverage": ("VERIFIED", "scripts/check_field_coverage.py + protocol-field-matrix.json"),
    "REQ-TEST-fixture-provenance": ("VERIFIED", "ensure_panel_fixture_provenance.py + panel *.meta.json"),
    "REQ-DEVICE-tunnel-start": ("EXTERNAL_BLOCKED", "needs interactive VPN permission + live config on device E4788B50…; install/launch already PASS"),
}


def main() -> int:
    data = json.loads(REQ_PATH.read_text())
    reqs = data["requirements"]
    by_id = {r["id"]: r for r in reqs}
    missing = [i for i in UPDATES if i not in by_id]
    if missing:
        print("MISSING IDS:", missing, file=sys.stderr)
        return 1
    for rid, (status, evidence) in UPDATES.items():
        r = by_id[rid]
        r["status"] = status
        r["evidence"] = evidence
    REQ_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    from collections import Counter

    print(Counter(r["status"] for r in reqs))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
